### ISSUE TITLE
Alternate Formatters? Table, CSV, JSON

### ISSUE THREAD

**Issue by geoffreywiseman** [codiform/gh-actions-usage#7]
Are people trying to use the output in a different way, and want CSV, JSON or tabular format? Let me know.

**Comment by estahn** [comment]
Came here to request CSV output to do some Excel stuff. Basically I want to sort by highest usage, but alternative format would enable more possiblities.

**Comment by geoffreywiseman** [comment]
There's a PR (#25) for `TSV` that just came in -- I knew I'd filed an issue for this, and I either hadn't noticed your comment or possibly noticed and then forgot, but I'll take a look at the PR.

**Comment by geoffreywiseman** [comment]
@estahn Ok, so I've made a PR (#26) that expands on that somewhat -- does the TSV format look like it would give you what you'd want?

**Comment by geoffreywiseman** [comment]
I'll release the formatter change with TSV -- feel free to file requests for format changes or other formats. I considered doing JSON as part of this release, but makes sense to drive any additional formatters from the needs of actual users, rather than just me speculating about formats that might be useful, so if you have a need that isn't met with either of the current formatters and you'd like to propose a new formatter or a change to an existing formatter, let me know.
